### PR TITLE
Updated zh-hans folder contents, deleted zh_hans folder

### PR DESCRIPTION
**Pull request by xjmzx**
Updated quickfacts SLA &PDF files

- Adjusted type layout as with original design
- Used more legible font (
- Adjusted font weighting (regular, bold & black)

Moved contents of zh_hans into zh-hans, deleted zh_hans folder:

- Included both full-color and printer-friendly SLA & PDF in zh-hans folder
- Included  Songti.tcc in zh-hans folder
- Moved PSA folder, PingFang.ttc and pingfang.ttf font-files into zh-hans
- Deleted zh_hans

### CODE REVIEW

**Comment by erciccione** [comment]
Is this meant to supersede #35 ?

**Comment by xjmzx** [comment]
yes, this is meant the previous pullrequest 35, sorry for nor making that clear

**Comment by xjmzx** [comment]
@erciccione  I have closed 35

**Comment by xjmzx** [comment]
I think I answered your question on chat, didn't see it here. I think mostly should keep it consistent as a rule-of-thumb. Those terms that have no translation 'garlic encryption', for example, though it could be translated, it would not work as there is no reference to a definition in Chinese, yet! Everything else can be searched and is in the lexicon of crypto-enthusiasts.

**Comment by lh1008** [comment]
Yes @xjmzx, this was before I had already spoken with you. I forgot to update the comment. 

Thank you @erciccione for the merge. :)

**Pull request merged**
