### PR TITLE
Russian translation of the QuickFacts

### PR DESCRIPTION
**Pull request by v1docq47**
Translate:

- QuickFacts-printerfriendly_ru.pdf 100%
- QuickFacts-printerfriendly_ru.sla 100%
- QuickFacts_ru.pdf 100%
- QuickFacts_ru.sla 100%

Calling to review:
@monerorus @LvMsterfild @AJIekceu4 @TheFuzzStone

### CODE REVIEW

**Comment by lh1008** [comment]
Thank you very much @v1docq47. I will merge it and make a design review. Then I will give you comments. Great Job! I will leave the PR open so anyone who will give the review from the translation can do so. :)

**Comment by monerorus** [comment]
Вычитал. Пару мест только перефразировал бы, а в целом отлично.

**Comment by erciccione** [comment]
@lh1008 Every pull request should be first reviewed, then merged. You merged this PR before reviewing it. This is dangerous and doens't follow git's workflow. Also, you said you were going to leave the PR open for reviewers, but you merged it right after (and only few hours after it was opened)
Keep also in mind that PDF's can cointain malicious links.

We need to define an efficient workflow for this repository, PMing you on mattermost

**Comment by erciccione** [comment]
@monerorus In general, we should stick as much as possible to the [C4](https://rfc.zeromq.org/spec:22/C4/), Monero's code of conduct

**Comment by lh1008** [comment]
@erciccione thank you for the [C4](https://rfc.zeromq.org/spec:22/C4/). I will be reading the Monero's code of conduct and doing a CONTRIBUTING.md with the same code so we can have a better-organized workflow. 

@monerorus, I wasn't aware of how the workflow is done in Github and inside Monero. So I'm learning, @erciccione will helps us have a better workflow and he also told me that he added an option that before merging someone needs to do a review first. 

When I merged I was not aware of the "consequences", I thought by merging, contributors could just fork and then validate and review the work to submit changes or comments. I personally commit myself to learn and help these things not happen again. 

Thank you all for your comprehension.

**Pull request merged**
