### PR TITLE
Added missing breaking_monero transcriptions 

### PR DESCRIPTION
**Pull request by lh1008**
Hey @erciccione,

Added missing breaking_monero transcriptions:

- #'s 2,3,5,7,8,9,11,12, and 13

Also added bold to the initial names. The whole series needs an English review to confirm the whole text and to add or remove any audio mistakes.

>:)

*I added eps4 but it was already worked by @netrik182 in #147. So I left the document as is but I had to add a new commit and squashed everything again. Not sure if that will affect #147. Please let me know :).

### CODE REVIEW

**Comment by sanecito** [comment]
FWIW I did 5 (and 6) and am a native English speaker so can attest to the English for those (assuming copied from MO website). If people want, they can always audit though to make sure my ears aren't failing me.

**Comment by erciccione** [comment]
@lh1008 how do you prefer to procede for the review of these documents? Should we wait for a formal review of the english text from someone of the outreach workgroup?

**Comment by lh1008** [comment]
@sanecito will add you as a signer to this PR, will amend the commit in a moment. Thank you for helping out :). And yes, I copied the transcriptions from the MO website, including 5 and 6.

@erciccione not really sure how to proceed. I think we can merge and let anyone who wants to make the review to open an Issue or a PR with any suggested changes. When I started following some of the transcriptions I personally found some things that need to be added/removed/fixed, but I decided to open the PR with what we had already pushed to the MO site (https://www.monerooutreach.org/breaking-monero/). I'm sure we will need to make updates to the documents. Let me know what you think. If you prefer to make a review immediately before merging, we go ahead and make the review first, no trouble :).

**Comment by lh1008** [comment]
I was going to add another author - co-author but I was not able too. If anyone can help me out please let me know how to add someone else in the same commit using git. >:)

**Comment by lh1008** [comment]
This can be merged anyway >:)

**Comment by erciccione** [comment]
>  I decided to open the PR with what we had already pushed to the MO site

This seems like the best approach to me, but it's important at this point that a review of this text is made as soon as possible and uploaded on the website right after.
Merging this now.

**Pull request merged**
