### PR TITLE
Quickfacts pg.5 'développement' fixed

### PR DESCRIPTION
**Pull request by lh1008**
Hi,

Saw this misspelled word. Submitting changes. 

@el00ruobuob :)

### CODE REVIEW

**Comment by lh1008** [comment]
@el00ruobuob... ping :see_no_evil:

**Comment by el00ruobuob** [comment]
For some reason I didn't see the first ping...

**Comment by lh1008** [comment]
Thank you @el00ruobuob it's ok. :)

**Comment by lh1008** [comment]
Thank you @erciccione :)

**Pull request merged**
