### PR TITLE
Merge `monero-meetup-kit-localization` and `Monero-Flyer` repos

### PR DESCRIPTION
**Pull request by erciccione**
As for monero-ecosystem/meta#31, merging the 2 repositories into this one. I added a readme inside `meetup-kit`, with instructions for translators/editors and a preview of the flyer.

The commit history of the two repositories is preserved. The relevant commits who actually make changes to this repo are the last 5: (8409f55) a25ec6f 01a7b4e e57091f 780b035

I also added a badge in the main review to keep track of the size of the repository, since it's still very big (see #31).

### CODE REVIEW

**Comment by lh1008** [comment]
Waiting for sgp to take a look at it.

**Comment by erciccione** [comment]
Will fix that typo soon. We have no rush to merge this btw, take your time for the review.

**Comment by lh1008** [comment]
I see we might have the same size issue with the .sla files, .sla files ocuppy a lot of space. We might consider to work the same as we are doing inside the repo, leaving only the .sla english 'en' file and adding the pdfs of every language and a .md file for each. What do you think?

**Comment by erciccione** [comment]
@lh1008 Yes, i think that's the best long-term solution, we could open an issue right after merging this PR, to keep track of the conversion.

**Pull request merged**
