### PR TITLE
Transcription for Moderating Monero at MoneroKon

### PR DESCRIPTION
**Pull request by netrik182**
on-behalf-of: @JOhNKmus

Reviewers: @netrik182 and @lh1008

### CODE REVIEW

**Comment by lh1008** [comment]
I'll start working on this.

**Comment by lh1008** [comment]
Opened a Pull Request (https://github.com/netrik182/outreach-docs/pull/2) in @netrik182 repository to merge this PR.

**Comment by netrik182** [comment]
@lh1008 merged

**Comment by lh1008** [comment]
Thank you @netrik182. Will be merging it right away.

**Pull request merged**
