### PR TITLE
Added PSA portuguese .sla files

### PR DESCRIPTION
**Pull request by lh1008**
Hi @erciccione,

Portuguese pt_PT translation for review. 

Still missing tiff portuguese headers and design edits. This is just for translation review.

### CODE REVIEW

**Comment by erciccione** [comment]
@rmbb @malmen Could you take a look at this if you have a minute?

**Comment by rmbb** [comment]
Hey all, translations were all made by me so aí would appreciate a review from other member ;)

Thanks.

Encrypted ProtonMail Mobile

**Comment by lh1008** [comment]
Hey @erciccione,

I'm trying to add "rmbb" as an author and I receive the message:
>git commit --amend --author "rmbb"
fatal: --author 'rmbb' is not 'Name <email>' and matches no existing author

**Comment by erciccione** [comment]
Sorry my bad, the flag should be used with this syntax: `--author="Author Name <email@address.com>"`

**Comment by lh1008** [comment]
@erciccione have not been able to do it...sorry...

>git commit --amend --author "rmbb rmbb@github.com"
fatal: --author 'rmbb rmbb@github.com' is not 'Name <email>' and matches no existing author

>git commit --amend --author "rmbb@github.com"
fatal: --author 'rmbb@github.com' is not 'Name <email>' and matches no existing author

>git commit --amend --author="rmbb rmbb@github.com"
fatal: --author 'rmbb rmbb@github.com' is not 'Name <email>' and matches no existing author

>git commit --amend --author rmbb
fatal: --author 'rmbb' is not 'Name <email>' and matches no existing author

>git commit --amend --author @rmbb
fatal: --author '@rmbb' is not 'Name <email>' and matches no existing author

>git commit --amend --author rmbb@github.com
fatal: --author 'rmbb@github.com' is not 'Name <email>' and matches no existing author


Not sure what else to do...

**Comment by erciccione** [comment]
`git commit --amend --author "MB <32343762+rmbb@users.noreply.github.com>"`, this is what git tells me looking his past commits, but `git commit --amend --author "rmbb <>"` would have been acceptable.

**Comment by lh1008** [comment]
Thank you @erciccione, I was finally able to do it. Not sure why I couldn't do it.

@rmbb added you as the actual author of the translations. I didn't know we were able to do it.

**Comment by rmbb** [comment]
No worries :)
Appreciate your effort on this!

Encrypted ProtonMail Mobile

**Comment by lh1008** [comment]
Thank you guys :+1:

**Pull request merged**
