### PR TITLE
Update Quick Facts (French)

### PR DESCRIPTION
**Pull request by el00ruobuob**
This is the french part of #59

Sorry for beeing late submitting this.

### CODE REVIEW

**Comment by el00ruobuob** [comment]
Ready for review @erciccione

**Comment by lh1008** [comment]
Thank you @el00ruobuob.

**Comment by lh1008** [comment]
@el00ruobuob were you able to see this review?

**Comment by el00ruobuob** [comment]
Sorry i missed it. On my way to update.

**Comment by el00ruobuob** [comment]
@lh1008, just did the updates according to @assylias review.

**Comment by lh1008** [comment]
Thank you @erciccione

**Pull request merged**
