### PR TITLE
Readme: add erciccione and xmrhaelan to the list of maintainers of the repo + rename README and fix typo

### PR DESCRIPTION
**Pull request by erciccione**
This PR add me as co-coordinator of this repository

edit:
I added two more commits, one change the name from `README.md` to `README_i18n.md`. This to differenciate the file from the main readme. The second commit fix a typo

### CODE REVIEW

**Comment by erciccione** [comment]
@xmrhaelan Would you like to be added as maintainer as well? You are the coordinator of the outreach workgroup afterall

**Comment by erciccione** [comment]
Adding you now. not a problem if you can't contribute much, but at least your reviews will be as maintainer

**Comment by xmrhaelan** [comment]
Ok thanks!

**Comment by erciccione** [comment]
Added

Paging @lh1008

**Comment by erciccione** [comment]
@xmrhaelan I merged this PR, you only need to accept the invitation i sent you and you will be a maintainer

**Comment by lh1008** [comment]
Great!

**Pull request merged**
