### PR TITLE
Zh-hans printerfriendly and design edits

### PR DESCRIPTION
**Pull request by lh1008**
Hi,

Did design edits and added, pdf's, and also did printer-friendly version. 

@xjmzx if you would like to take a look and review them is ok. If you need any help let me know. :)

@erciccione take a look at them and let me know if you have any questions. I noticed about two folders (zh-hans and zh_hans) for the chinese versions, so I will first make this PR and then merge them together.

Thank you.

### CODE REVIEW

**Comment by xjmzx** [comment]
Read over the PDF files carefully, I can't see any errors/typos.
One small suggestion maybe would be to change the title to Chinese: i.e:

Monero Quick Facts > 门罗币 —— 快速事实

However, I know the title is not text but a graphic.
Also, Core Principals > 核心原则

This is just a small point but with regards to not wanting to alienate any potential readers.
The font used looks great! 

By the way if needed, tell me which repository I can place the translation terminology file into.

**Comment by lh1008** [comment]
Thank you @xjmzx :)

I will be adding those changes, and one last thing, could you please point me out which are these words in the second page:
- open-source project
- decentralized team
- blockchain
- dynamic block size
- capital control
- ring signatures
- ring confidential transactions
- stealth addresses
- fungible

*Those have a link attached to it. 
I haven't :see_no_evil: oups. I forgot, let me find someone else to help us out, just in case.

**Comment by lh1008** [comment]
@xjmzx  about:

>The labels, 'Full Color' / 'Printer Friendly' need swapping perhaps?

They are actually links redirecting to the "Full version" or/and the "Printer Friendly". So they are ok, if someone else wants to go to the "Printer Friendly" from the "Full Version" they just click on the word link.
If this can also be translated would be great.

**Comment by lh1008** [comment]
@xjmzx I just added the translations for "Quickfacts" and "Core principles". :)

**Comment by xjmzx** [comment]
1. opensource		                                 开源性
2. decentralized team                              一群**去中心化**的 
3. dynamic block-size                             态块的大小
4. capital control	                                 资本控制
5. ring signatures		                         环签名
6 ring confidential transactions		环保密交易
7 stealth addresses	                         隐秘的地址
8 fungible		                                 可互换性
9. blockchain 		                                 区块链

text_highlights_1-9

**Comment by xjmzx** [comment]
Can add this terminology into the list of translations terms, if you have a moment to assist with PR @lh1008

**Comment by lh1008** [comment]
@xjmzx did the final link edits, thank you. Just waiting for your approval to merge it. 

@erciccione only missing approval in order to merge. Final link edits done. 

Thank you all for your contributions :)

**Comment by lh1008** [comment]
@erciccione squashed all commits with final edits. We should first merge this PR to add more edits. 

@xjmzx please review the final edits and approve the changes. The first PR you made #24 had the full version and not the printer-friendly. I added the printer friendly with this PR.

**Comment by lh1008** [comment]
Ok done @erciccione. Sometimes I forget. I will try not to forget.

**Comment by lh1008** [comment]
Thank you @erciccione

**Pull request merged**
