### PR TITLE
Quick Facts French Translation

### PR DESCRIPTION
**Pull request by el00ruobuob**
All is in the tittle.

While translating, i found two outdated facts (as of 7/26/2018) :

* MRL has published **6** reports, not 5
* Ledger **is** supported since CLI 0.12.2 and GUI 0.12.3

This version contains those correction.
However, i'll let you correct English and Spanish @lh1008.

### CODE REVIEW

**Comment by lh1008** [comment]
Awesome! I haven't made the changes in the original files, I will be doing them soon.

**Comment by lh1008** [comment]
I saw two `fr` links from the getmonero.org are not displayed yet.

 - Chaine de blocks

https://getmonero.org/fr/resources/moneropedia/blockchain.html-technology/404 


 - fongible

https://getmonero.org/resources/fr/moneropedia/fungibility.html

Do you know if this links are already being worked, or they have issues un the monero-site?

**Comment by el00ruobuob** [comment]
Those two looks like copy and paste typos. I will correct them quickly tonight or tomorrow. Sorry about that.

**Comment by el00ruobuob** [comment]
@lh1008, it was added in #monero-project/monero-site/817 but the site has not been rebuilt since. It's a matter of weeks now with the upcoming 0.13

**Comment by lh1008** [comment]
Ok, thank you for the response. I noticed a strange tag when building the website from jekyll that I would like to make a notice about. Will be doing a new issue on monero-site also. :) What is 0.13?

**Comment by lh1008** [comment]
Yes take a look. 

en_blog

en_press


I haven't changed anything. I noticed it last week, when I was looking at the Press-kit section to add the quickfacts pdf. I then went to all the links inside the website and found that the "Recent News/ All Blog Post" also has the same **@lang_tag_en**, and it displays in all languages too (es,fr,it,pl, and ar). I also notified @rehrar about it.

**Comment by el00ruobuob** [comment]
It should be removed by moneropedia ruby script

**Comment by el00ruobuob** [comment]
Did you git clone in a new folder? Otherwise it might be using the old script.

**Comment by el00ruobuob** [comment]
Oh I have the same behavior here. Some pages are not going through the script while I added the tag to them. Will fix this, but an issue should be appropriate to track them all.

**Comment by lh1008** [comment]
Ok, I will be opening the issue tracking all of them. I was not sure how to fix it, but I was trying to troubleshoot it, with no success. 

>Did you git clone in a new folder?

yes :)

I'm working on adding the quickfact pdf to the press-kit section. Already added some lines. I have taking a bit because I'm still learning how to update the website. If I need help maybe I will be bothering you through chat :P.

**Pull request merged**
