### PR TITLE
Add quickfacts in traditional Chinese

### PR DESCRIPTION
**Pull request by Lafudoci**
No printerfriendly version yet, is there easy way to convert it into printerfriendly version? Or I need to manually make one?

### CODE REVIEW

**Comment by Lafudoci** [comment]
BTW, There is something confusing to me in the quickfacts doc.  what's the ethos of the monero and how is it related to hardware wallet? At page 4 bottom.

**Comment by Lafudoci** [comment]
>You will have to manually edit it. You could also ask @hrumag, he edited the printerfriendly in a different way(take a look at PR #38 ), we merged it, and I just worked the design editions once the text was added to the file. Or you can just open the printer friendly and copy from the full-color version the text frames to the printer friendly. Not sure if this could answer your question.

Yes, thanks. I'll do it later and commit to this PR. And I'll also invite some people for reviewing translation after in the mean time.

>The Monero ethos is related to open source ideology. The hardware wallet kastelo.org is a hardware funded by the Monero community to be an open source hardware wallet, and this is what identifies the Monero open source ethos.

OK, and I finally find [this](https://www.reddit.com/r/Monero/comments/8ubsnh/developing_a_core_ethos_for_the_monero_community/). Because there is an famouse OS for crypto mining called [ethOS](http://ethosdistro.com/). That's why I was confusing.

**Comment by xjmzx** [comment]
@Lafudoci @lh1008 For the Printer Friendly, I don't know if the simplified Chinese layout would be radically different to the traditional Chinese, but couldn't those also be used as templates? Then again, it may not be easier to strip out the text and check the links? But surely it would be easier to start with the template in another language, rather than from scratch?

**Comment by Lafudoci** [comment]
@xjmzx Thank you for kindly suggestion, however, I found that editing color is more easier than transfer all the text box between files.
@willgoodsinica Thanks for your review.
@lh1008 Printerfriendly version uploaded, I believe they're ready :)

**Comment by lh1008** [comment]
Thank you all guys for the comments and work, I will be checking the technical details later today so we can merge it into the repo. :) :+1:

**Pull request merged**
