### PR TITLE
Reedited .sla & PDF, deleted unused fontfile

### PR DESCRIPTION
**Pull request by xjmzx**
- Used Songti Font, regular, bold, black for headings/sub
- Created Chinese Heading on (p1)
- Reformatted links to copy (p2)
- Changed text color of main copy to highlight links (p2)

- Deleted unused Font PingFang

### CODE REVIEW

**Comment by erciccione** [comment]
@lh1008 Does this conflicts in any way with #33 ?

**Comment by erciccione** [comment]
@xjmzx This is only about the printerfriendly quickfact. Do you plan to update the normal version once #27 is merged? (please, leave an approval there if that PR is ok, so i can merge it)

**Comment by xjmzx** [comment]
@erciccione I forgot that I still need to update the full-colour version, I will get that done and update the PR request before merge. Sorry, I'm slowly getting a crash course in Github workflow!

@lh1008 is there another .sla file for the full colour version?

**Comment by lh1008** [comment]
Hi @erciccione 

>@lh1008 Does this conflicts in any way with #33 ?

Chinese fonts have not been included in the 'fonts' folder, so this won't have conflicts with #33. 

@xjmzx 
I think is better to merge #27 first. Then you can download it and from that one you can make the edits you are suggesting so we can have a normal workflow.  I'm also waiting to merge #27 to merge the [zh_hans](https://github.com/monero-ecosystem/outreach-docs/tree/master/monero-outreach-docs/translations/zh_hans) folder to this one you have been working on [zh-hans](https://github.com/monero-ecosystem/outreach-docs/tree/master/monero-outreach-docs/translations/zh-hans/quickfacts).

>@lh1008 is there another .sla file for the full colour version?

The first PR you made #24 did not have the printer-friendly. So I added the printer friendly in the PR #27. We should first merge it and you cand then download it, and make the edits and change the fonts you like. Then make another PR like this one and we make the review of those changes. 

If there are any questions please let me know :).

**Comment by erciccione** [comment]
Please rebase

**Comment by xjmzx** [comment]
@erciccione rebased and created new pull request (#39)

**Comment by erciccione** [comment]
@xjmzx What do you mean? is this obsolete? or #39 integrate this pull request?

**Pull request closed without merging**
