### PR TITLE
[IT-QuickFacts] Translation Update - first issue

### PR DESCRIPTION
**Pull request by hrumag**
In response of #59.
Have a good day @lh1008 @erciccione @xmrhaelan.

### CODE REVIEW

**Comment by erciccione** [comment]
Thanks @hrumag :)

**Comment by lh1008** [comment]
Thanks @hrumag :)

**Comment by hrumag** [comment]
Let me know if squash is needed.

**Comment by lh1008** [comment]
Yes @hrumag a squash would be better :).

**Pull request merged**
