### PR TITLE
Pull request with erciccione's help

### PR DESCRIPTION
**Pull request by krista89**
Thank you!

### CODE REVIEW

**Comment by erciccione** [comment]
You are welcome! and congratuletion for your first pull request :)

Hey @ProkhorZ if you hate time, would be great to have this reviewed

**Comment by lh1008** [comment]
Congrats @krista89 :).

**Comment by ProkhorZ** [comment]
The PDFs are still in English. Will they be created in Dutch after merging?

I took a look at the raw text, and I'm sorry, I don't have the time to review this in the current state. 
@krista89 Could you copy and paste the text into a word processor in order to check the spelling?
Then if you could find another reviewer to improve the translation, I might be able to make it production-ready in November.

Here's a sample of the spelling errors I found at first glance:
- kunniet 
- leverancies 
- orginele 
- gemakkleijke 
- creeeren 
- Belongings tempo
- portomonees 
- toevvoegen 

It's great that you want to contribute. What would you say is your talent if it isn't writing or coding? If it's doing the actual outreach IRL, let's have you do that once we have a translation.

**Comment by erciccione** [comment]
Ping @krista89

**Comment by lh1008** [comment]
Hey @krista89 :) 

Are you going to finish the translation?

**Comment by lh1008** [comment]
Hi @krista89,

The PR has been opened now for 24 days and we haven't received any new updates. Are you still interested? We will give the PR a deadline of 24hrs to close it. 

Thank you. :)

**Comment by lh1008** [comment]
Closing, for no activity.

**Pull request closed without merging**
