### PR TITLE
Wallet primer pt br.md

### PR DESCRIPTION
**Pull request by nelsonrenan**

### CODE REVIEW

**Comment by lh1008** [comment]
Hey @nelsonrenan,

Thank you for submitting the Pull Request. Pinging @botoserelepe or @netrik182 for review. 

Nelson please remove the following commits,  [
57ad1a9 ](https://github.com/monero-ecosystem/outreach-docs/pull/224/commits/57ad1a992ae190580e9f684da2fda728659434ce), [
334fa78 ](https://github.com/monero-ecosystem/outreach-docs/pull/224/commits/334fa780627b9ceac9431381b10e4e8cdc0c9cfb), [
e72c768 ](https://github.com/monero-ecosystem/outreach-docs/pull/224/commits/e72c768d575414fff10d19a74053367afde6fb5c).

If you need assistance, please let me know.

**Comment by botoserelepe** [comment]
Hey @lh1008 @nelsonrenan ,

I can review this one. :)

**Comment by erciccione** [comment]
Don't worry about the conflict here. I'll resolve it before merging.

**Review by lh1008 — DISMISSED** [review]
Everything looks okay. Thank you @nelsonrenan and @botoserelepe.

**Review by erciccione — APPROVED** [review]
Conflict resolved.

**Pull request merged**
