### PR TITLE
Italian quickfacts design edits and links corrections

### PR DESCRIPTION
**Pull request by lh1008**
Hi @erciccione,

Did some design edits and removed some links and left them the same as the original English links version. 

@hrumag thanks a lot for your work. You can take a look at how the final version came out. :).

Thank you all.

### CODE REVIEW

**Comment by hrumag** [comment]
Thanks @lh1008!

Il giorno ven 2 nov 2018, 00:13 lh1008 <notifications@github.com> ha
scritto:

**Comment by lh1008** [comment]
@hrumag what do you mean with this one? What would the final words look like?

"Storia di Monero" Section
>[...] tenendo anche conto

One space should be removed between "tenendo" and "conto".

* tenendoanche conto?
* tenendo ancheconto?

**Comment by lh1008** [comment]
Thank you @hrumag, I didn't understand. Maybe I was to lazy to look. I will doing the commit right away with the corrections. Thank you :). :+1:

**Comment by lh1008** [comment]
@hrumag did the corrections. Thank you again. Could you please approve the changes :).

@erciccione this just needs approval to merge. 

Thank you guys.

**Comment by lh1008** [comment]
Thank you @erciccione.

**Pull request merged**
