### PR TITLE
Missing translations en_md files

### PR DESCRIPTION
**Pull request by lh1008**
Hey @erciccione 

Here is the Loca-Mesh interview located in the `en-archive` folder. @netrik182 please check it out. We have to work out the translations for it. 

I will be working the `es` translation for it. 

Thank you.

### CODE REVIEW

**Comment by netrik182** [comment]
Hi @lh1008. Thanks for the ping. I'll work on `pt-br`

**Comment by erciccione** [comment]
I don't see any value in having this interview translated. It's not an informative article i don't see why the international community would care.

Other articles came out before this one and would make sense to have them translated, like:

- https://www.monerooutreach.org/stories/dandelion.html
- https://www.monerooutreach.org/stories/RPC-Pay.html
- https://www.monerooutreach.org/stories/getting-started-helping-monero.html

All the articles above, beside being informative and useful to an international community, had very good feedback and were very appreciated by the community. The Locha interview didn't rise any particular interest and as i said before, it's not informative. Based on what criteria the outreach workgroup is dedicating translator resources on this article instead of the 3 i mentioned above? Especially if we consider how few translators are at the moment.

**Comment by lh1008** [comment]
Hey @erciccione,

File upload of every produced document is necessary inside the Monero Outreach workgroup. Translations have always been worked in order of produced content. 

- https://www.monerooutreach.org/stories/dandelion.html
- https://www.monerooutreach.org/stories/RPC-Pay.html
- https://www.monerooutreach.org/stories/getting-started-helping-monero.html

Dandelion, RPC-Pay, and Getting started helping monero, are going to be pushed to the repository the same as Loca Mesh interview is being pushed. The criteria to choose what is being translated has always been based on what is being produced inside the workgroup and not of what the Monero community considers important. Only publishing what the Monero community considers important could bias/influence what a specific group considers important and not what other groups could consider important. This is based on the decentralization nature of what Monero stands for and what the cryptocurrency community stands for.

**Comment by lh1008** [comment]
Anyway your comment is being taken into consideration. I will upload the other files and start with the following:
- Helping Monero
- RPC-Pay
- Dandelion

Thank you for your comments and helping the Monero Outreach workgroup.

**Comment by erciccione** [comment]
> Translations have always been worked in order of produced content.

I don't understand, isn't the Locha article the last one produced?

I think you are being quite defensing in your comment, but actually i only asked the criteria that was used to prioritize this work instead of others. Your answer seems to be, we prioritized this, because of decentralization, which is not an answer :) Also, how can that be the case if the content is translated in chronological order? Seems like this approach is working the other way round now. The RPC-Pay article for example, was posted on the end of January this year, but the Locha article is from a couple of weeks ago.

Beside, i never questioned the fact that the article is being published, i don't see any problem with that obviously, i'm only talking about translation efforts.

**Comment by erciccione** [comment]
To clarify my position: if you guys changed system (from chronological) and prefer to prioritize the translation of this article, that's your choice and prerogative, as you have your own system, but i personally won't suggest translators to prioritize this article, since i think translation effort should be directed to more useful content. I would prioritize translations of the published articles in this order:

1. Helping Monero
2. RPC-Pay
3. Dandelion++
4. Locha

**Comment by erciccione** [comment]
@lh1008 Anyway, i guess this is the article as it was published on the website, so can already be merged, right?

**Comment by lh1008** [comment]
Well, I guess my response was a little defensive. Please accept my apology on this. 

We actually don't have a defined criteria on how to translate, I thought to start from the last could be a way to move faster with what has been published because the last article is the last that the community received. 

I'll be adding the missing articles in this PR, so please let me add them so we can push everything together.

**Comment by lh1008** [comment]
@erciccione 

I just added **RPC-pay** and **Dandelion**. I'm missing _**Getting started**_, I'll be posting it tomorrow I have to get myself studying, I'm half-way on it.

Forgive my rudeness.

**Comment by lh1008** [comment]
@netrik182 let me push [_**Getting started**_](https://www.monerooutreach.org/stories/getting-started-helping-monero.html) file to the PR and we can start on working on that one first. :)

**Comment by erciccione** [comment]
No needto apology, i just wanted to be clear that i'm not attacking anybody, just giving suggestions :)

Ok then, will wait for the last file then i will merge.

**Comment by lh1008** [comment]
Hey @erciccione,

This should be ready to merge. Just finished adding getting_started_en.md file. 

Thank you.

**Comment by lh1008** [comment]
Will keep on adding the rest of the files, but this one can be merged.

**Pull request merged**
