### PR TITLE
Russian Translations Update

### PR DESCRIPTION
**Pull request by v1docq47**
@lh1008, @erciccione, I updated the old translations and added new ones ;)

Edit (update) and fix Russian translations:
- outreach-docs\monero-outreach-docs\translations\ru\archive\dandelion_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\archive\getting_started_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\archive\how_to_buy_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\archive\loca_mesh_interview_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\archive\reuters_response_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\archive\rpc_pay_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\archive\triptych_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\archive\wallet_primer_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\archive\we_accept_monero_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\PSA\files\exchange\exchange_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\PSA\files\learning\learning_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\PSA\files\wallet\wallet_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\PSA\PSA _ru_headers.md
- outreach-docs\monero-outreach-docs\translations\ru\storyboard\blockchain_gender_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\storyboard\fundamental_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\storyboard\giant_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\storyboard\randomX_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\storyboard\refuge_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\storyboard\swot_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\storyboard\tool_for_renewal_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\storyboard\wallet_quickstart_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\breaking_monero\01_introduction_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\breaking_monero\02_ring_signature_intro_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\breaking_monero\03_chain_reactions_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\breaking_monero\04_chain_splits_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\breaking_monero\05_input_selection_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\breaking_monero\06_unusual_ringsize_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\breaking_monero\07_remote_nodes_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\breaking_monero\08_timing_attacks_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\breaking_monero\09_poisoned_outputs_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\breaking_monero\10_public_mining_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\breaking_monero\11_mailbag_episode_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\breaking_monero\12_in_output_metadata_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\breaking_monero\13_blockchain_explorer_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\monero-konferenco-2019\Achieving_Secure_Deployment_of_High-Stakes_Software_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\monero-konferenco-2019\ASIC-Resistant_Proof_of_Work_Fact_or_Fantasy_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\monero-konferenco-2019\Bringing_Privacy_Mainstream_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\monero-konferenco-2019\Challenges_in_Building_Software_with_Monero_Code_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\monero-konferenco-2019\Dandelion_Onions_Protecting_Transaction_Privacy_in_Monero_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\monero-konferenco-2019\Lelantus_New_Protocol_for_Private_Transactions_with_Hidden_Origins_and_Amounts_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\monero-konferenco-2019\Monerokon_Madness_Schnorr_Schadness_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\monero-konferenco-2019\Network_Attacks_Obfuscation_Of_Payment_System_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\monero-konferenco-2019\Omniring_Scaling_Up_Private_Payments_Without_Trusted_Setup_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\monero-konferenco-2019\Perfect_Privacy_or_Strong_Deniability_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\monero-konferenco-2019\Spam_Mitigation_The_Challenge_of_Private_and_Permissionless_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\monero-konferenco-2019\The_Elephant_In_The_Pool_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\monero-konferenco-2019\The_Embedded_Future_of_Monero's_PoW_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\monero-konferenco-2019\Transaction_Efficiency_Then_And_Now_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\monero-konferenco-2019\Visualizing_Monero_A_Figure_is_Worth_a_Thousand_Logs_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\website-sections\breaking_monero_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\website-sections\guerrila_toolkit_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\website-sections\investors_resources_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\website-sections\monero-typography_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\website-sections\monero_konferenco_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\website-sections\resources_ru.md

Added new Russian translations:
- outreach-docs\monero-outreach-docs\translations\ru\merchants\accept_monero_stickers_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\merchants\payment_processors_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\merchants\retail_resources_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\storyboard\bitcoin_founder_created_monero_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\storyboard\china_and_west_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\storyboard\monero_konferenco_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\breaking_monero\14_subaddress_association_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\transcriptions\monero-konferenco-2019\Money_at_the_Edge _How_People_Stay_Afloat_in_Venezuela_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\website-sections\404_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\website-sections\monero_best_practices_en.md
- outreach-docs\monero-outreach-docs\translations\ru\website-sections\monero_commmunity_gallery_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\website-sections\monero_merchants_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\website-sections\monero_shop_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\website-sections\news\algorithm_battle_ciphertrace_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\website-sections\news\town_forge_ru.md
- outreach-docs\monero-outreach-docs\translations\ru\website-sections\videos\videos_ru.md

Moved files:
- `outreach-docs\monero-outreach-docs\translations\ru\archive\monero_means_money_ru.md` to `outreach-docs\monero-outreach-docs\translations\ru\website-sections\news\monero_means_money_ru.md` (According to 'EN" folder)
- `outreach-docs\monero-outreach-docs\translations\ru\website-sections\news_room_ru.md` to `outreach-docs\monero-outreach-docs\translations\ru\website-sections\news\news_room_ru.md` (According to 'EN" folder)

Renamed files:
- outreach-docs\monero-outreach-docs\translations\ru\PSA\files\mining\mine_support_network_ru.md (Added 'RU" tag)

Ping to review:
@LvMsterfild @monerorus

### CODE REVIEW

**Comment by erciccione** [comment]
Were this already reviewed or done in collaboration with Russian-speakers? Just to know the status of things. These are a lot of changes :)

**Comment by v1docq47** [comment]
Yup, I have already translated and published some of this on XMR.RU.
If necessary, I can post links to XMR.RU :)

**Comment by erciccione** [comment]
>  If necessary, I can post links to XMR.RU :)

It's not necessary, but would be appreciated. Mostly for the records and future reviewers.

**Comment by v1docq47** [comment]
Links to articles on [XMR.RU](https://xmr.ru/)
[Monero Payment Processors](https://www.monerooutreach.org/merchants/monero-payment-processor-guide.html) --> [Платёжные операторы Monero](https://xmr.ru/threads/1336/)
[New Evidence Suggests Bitcoin Founder Satoshi Also Created Monero](https://www.monerooutreach.org/stories/satoshi-van-saberhagen.html) --> [Новое свидетельство того, что Monero также была создана Сатоши Накомото](https://xmr.ru/threads/1276/)
[Monero in China and the West](https://www.monerooutreach.org/monero-china-west.html) --> [Monero в Китае и на западе](https://xmr.ru/threads/1203/)
[MoneroKon 2019: Money at the Edge: How People Stay Afloat in Venezuela](https://www.monerooutreach.org/monero-konferenco/jamaal-montasser.html) --> [MoneroKon 2019: Деньги на краю - как люди остаются на плаву в Венесуэле](https://xmr.ru/threads/1068/)
[404 : Page Not Found](https://www.monerooutreach.org/404-US-en.html) --> [Ошибка 404: Страница не найдена](https://xmr.ru/threads/1390/)
[Algorithm Battle Flares Between CipherTrace and Monero](https://www.monerooutreach.org/news/ciphertrace-monero.html) --> [Разгорается битва алгоритмов между CipherTrace и Monero](https://xmr.ru/threads/1419/)
[Townforge Private Blockchain Game Testnet Launched](https://www.monerooutreach.org/news/townforge-blockchain-game.html) --> [Состоялся запуск приватной блокчейн-игры Townforge](https://xmr.ru/threads/1447/)

**Comment by LvMsterfild** [comment]
Yes, it's already on our site. I read and edited most of materials.

**Review by LvMsterfild — DISMISSED** [review]

**Review by LvMsterfild — APPROVED** [review]

**Review by lh1008 — APPROVED** [review]
Great work @v1docq47 and @LvMsterfild. Thanks :)

**Review by lh1008 — APPROVED** [review]
Approved

**Pull request merged**
