### PR TITLE
Quickfacts simplified chinese zh-hans reviewed.

### PR DESCRIPTION
**Pull request by lh1008**
Co-authored-by: almutasim <almutasim@users.noreply.github.com>

Hi @erciccione,

This was a review made by @almutasim and suggests some important changes. I will ping our first contributor to take a look at it, and maybe if you know someone who might help will be of great help. 

*Btw, before merging, if the suggested text is approved I will add the printer-friendly version so we won't have two commits for this. 

Thank you :).

@xjmzx could you please take a look at the suggested changes. The author explained to me that there were some words that might not fit inside the text and that he found some other translation details that were either missing or have a better grammatical structure. Please feel free to leave your comments.

Thank you :)

### CODE REVIEW

**Comment by xjmzx** [comment]
Hello. Yes. Have looked at the reviewed changes. Fully comply with the suggested updates. There are suggestions which may work better. 

This being my first translation project through Github, may have missed some detail when things were reformatted, switching fonts etc. As far as the grammatical changes go, I think the changes read better/more succinct.

**Comment by xjmzx** [comment]
Please let me know if you need any help with the printer friendly version

**Comment by lh1008** [comment]
@xjmzx could you please approve the changes? :)

**Comment by lh1008** [comment]
Btw, @xjmzx great job, thank you for the review :).

**Comment by lh1008** [comment]
Hi @erciccione,

Printer-friendly version added. 

:)

**Comment by erciccione** [comment]
Is it ready to be merged?

**Comment by lh1008** [comment]
It should @erciccione. @xjmzx already reviewed but it seems he forgot to approve.

**Comment by lh1008** [comment]
Thank you @erciccione, @xjmzx, and @Almutasim. 

Great work guys :).

**Pull request merged**
