### PR TITLE
Storyboard wallet_quickstart Simplified Chinese

### PR DESCRIPTION
**Pull request by lh1008**
Hey @erciccione,

Submitting the storyboard wallet_quickstart_zh-hans.md file. Sign on behalf of @almutsim.

Needs a review. 

Maybe @Lafudoci or @XMRNoblesse can help us out in the review. 

:)

### CODE REVIEW

**Comment by lh1008** [comment]
Ready for review. Pinging @xjmzx @Lafudoci and @XMRNoblesse if anyone of you can check it out. Thank you.

**Comment by lh1008** [comment]
Thank you @XMRNoblesse. Pinging @almutsim to check the review.

**Comment by lh1008** [comment]
Pinging @almutsim to approve the suggested changes.

**Comment by erciccione** [comment]
What's the status of this? waiting for @al-mutasim review or ready to merge?

**Comment by lh1008** [comment]
We are waiting for @al-mutasim to approve the changes.

**Comment by al-mutasim** [comment]
Looks great. The paragraph starting on line 30 should be changed to the following two paragraphs (to clarify the use of keys):

需要注意的是门罗币有两种密钥：一种是查阅密钥，用于查看转账过程，但查阅密钥不能用于交易及提币；另一种是支付密钥，拥有了支付密钥您就拥有了这一笔门罗币，您可以对这笔门罗币进行提币及交易。

轻钱包也有两种类型:查阅密钥保护型和查阅密钥分享型。查阅密钥保护型轻钱包会保持您的查阅密钥完全私有，因此必须下载区块链，或至少下载在钱包创建日期之后的部分，以计算钱包中的门罗币的余额。另一方面，查阅密钥分享型轻钱包与运行远程节点的服务器共享查阅密钥，以计算服务器上钱包的结算情况。这些高效钱包有时被称为钱包应用程序。如果由于允许查阅交易的过程，而导致运行拥有查阅密钥的远程节点的服务器不受信任，那么查阅密钥的分享就会导致隐私性的降低。不过，请注意，有时钱包持有人共享用于审计的查阅密钥——它不允许进行门罗币转账。

Also, line 93 should start Trezor... (rather than Ledger...)

Other than that, it looks good.

**Comment by lh1008** [comment]
@al-mutasim did the changes in line 30 and 93. This should be then ready.

>:)

**Pull request merged**
