### PR TITLE
Translation dandelion_en for dandelion_pt-br

### PR DESCRIPTION
**Pull request by nelsonrenan**

### CODE REVIEW

**Review by erciccione — CHANGES_REQUESTED** [review]
Could you change the name of the commit specifying you are translating into pt-br?

**Comment by nelsonrenan** [comment]
Ready. Changed.

**Comment by erciccione** [comment]
You need to change the name of the commit itself. With git you can use `git commit --amend`, change the name then force push to your remote branch.

**Comment by nelsonrenan** [comment]
My local repository has been corrupted. I made a new pull request. Please disregard this.

The new pull request:

https://github.com/monero-ecosystem/outreach-docs/pull/251

**Pull request closed without merging**
