### PR TITLE
Removed 'Not applicable' to wallet 'en/ru' storyboard files

### PR DESCRIPTION
**Pull request by lh1008**
Hi @erciccione,

From the storyboard wallet files already added, removed the "Not applicable" that was added by mistake. 

>:)

### CODE REVIEW

**Comment by lh1008** [comment]
This can be merged fast.

**Comment by erciccione** [comment]
Was this closed on purpose or should be reopen?

**Comment by lh1008** [comment]
Yes @erciccione I closed it on purpose. Noticed that in the site the "Not Applicable" is part of the information inside the article. 
notapplicable

:)

**Comment by erciccione** [comment]
Got it, thanks for the clarification :)

**Pull request closed without merging**
