### PR TITLE
Konferenco Lelantus talk original transcription

### PR DESCRIPTION
**Pull request by JOhNKmus**
Hey @lh1008 

Transcription for:
Lelantus: New Protocol for private transactions with hidden origins and amounts based on DDH - Aram Jivanyan, Zcoin

Author @JOhNKMus

Taiga instance 225 
https://taiga.getmonero.org/project/xmrhaelan-monero-public-relations/us/225

### CODE REVIEW

**Comment by erciccione** [comment]
ping @lh1008

**Comment by lh1008** [comment]
Will start the review right away.

**Comment by lh1008** [comment]
I'm currently working on this review. Haven't finished it yet.

**Comment by erciccione** [comment]
@lh1008 I don't understand, why was a file uploaded on Taiga instead of making a normal review here?

**Comment by erciccione** [comment]
> thought the whole new text will help @JOhNKmus to push it easier

@lh1008 Since we are using GitHub for reviews, better stick to their review process. Mixing things is no good :)

**Comment by erciccione** [comment]
What's the status of this @JOhNKmus ?

**Comment by JOhNKmus** [comment]
@erciccione the review by @lh1008 has been committed, it should be ready to merge I believe.

**Comment by JOhNKmus** [comment]
Yeah I agree, I that was my bad. I think generally we shouldn't include who is speaking unless its a group discussion because its already implied who is speaking.

**Pull request merged**
