### PR TITLE
Stay Afloat transcription edited file name and added message to not t…

### PR DESCRIPTION
**Pull request by lh1008**
Hey @erciccione,

Added a message to not translate until the review is done and changed the file name.

Thanks 

:)

### CODE REVIEW

**Comment by erciccione** [comment]
Is this necessary? Wouldn't be enough to warn translators on the outreach channels? I don't know how many start translating by their own initiative

**Comment by lh1008** [comment]
@erciccione Russian translators start translating by initiative. It's really is not necessary but this needs a serious review. I will do it once I push Spanish Triptych, almost done with it.

**Comment by lh1008** [comment]
@erciccione https://github.com/monero-ecosystem/outreach-docs/pull/255

:laughing: 

:)

**Comment by v1docq47** [comment]
Ops...
I did the translation and voice acting of this episode for another year ago :D
Translation - https://xmr.ru/threads/1068/
Voice acting - https://youtu.be/5gn5RnZiJZs

**Review by erciccione — APPROVED** [review]
Let's remember to remove it after.

**Pull request merged**
