### PR TITLE
Ru

### PR DESCRIPTION
**Pull request by lh1008**
Hi @erciccione,

Did russian design edits(changed fonts 'freeserif' and 'ungraphic' for open source). Maybe this time we can make a review for the russian translation.

Thank you. :+1:

### CODE REVIEW

**Comment by erciccione** [comment]
Anybody who can review this? @monerorus @LvMsterfild @v1docq47

**Comment by v1docq47** [comment]
@lh1008 thanks! @erciccione I will do it today / tomorrow

**Comment by v1docq47** [comment]
All fine! the word Monero is missing on the first page.
monero

**Comment by lh1008** [comment]
Oh yes @v1docq47. :see_no_evil: I will add it right away. 

Thank you for your review :).

**Comment by lh1008** [comment]
Ok done. 

This just needs approval :)

@v1docq47 @erciccione

**Pull request merged**
